# FROM node:10.13-alpine
# ENV NODE_ENV production
# WORKDIR /usr/src/app
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# RUN npm install --production --silent && mv node_modules ../
# COPY . .
# EXPOSE 3000
# CMD node index.js



FROM node:12

WORKDIR /app

COPY package*.json ./


RUN npm install

COPY . .

CMD ["npm", "start" ]